{
 "title": "Beyond",
 "description": "Beyond dashboard",
 "tags": [
  "Beyond",
  "sql-monitor",
  "estate-management"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1d",
 "panels": [
  { "title": "North Star", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of monitored PostgreSQL instances seen each month",
   "type": "barchart",
   "description": "\"Licensed\" = as reported by \"licensedPostgresEnvironments\" and \"trial\" is the difference between \"postgresInstances\" and licensed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| where tobool(client_Type == \"SaaS\")==false\r\n| extend numPostgresInstances=toint(customDimensions[\"postgresInstances\"])\r\n| where numPostgresInstances > 0\r\n| summarize arg_max(timestamp, *) by user_Id, bin(timestamp, startofmonth(timestamp))\r\n| extend licensedInstances = toint(customDimensions[\"licensedPostgresEnvironments\"])\r\n| extend trials = numPostgresInstances-licensedInstances\r\n| summarize\r\n    licensed = sum(licensedInstances),\r\n    trial = sum(trials)\r\n    by bin(timestamp, startofmonth(timestamp))\r\n| sort by getmonth(timestamp) asc\r\n    ",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Monitored PostgreSQL Instances (in time window)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| where timestamp > $__timeFrom\r\n| summarize arg_max(timestamp, numPostgresInstances=toint(customDimensions[\"postgresInstances\"]), isSaas=tobool(client_Type == \"SaaS\")) by user_Id\r\n| where numPostgresInstances > 0\r\n| summarize\r\n    sumif(numPostgresInstances, isSaas == false)\r\n    // ,sumif(numPostgresInstances, isSaas)",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average # instances monitored per customer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let mappings = customEvents\r\n  | where name == 'monitorinstallation.identifiers'\r\n  | where customDimensions !has 'DeveloperMode'\r\n  | where parse_version(application_Version) > parse_version(\"13.0.15.0\")\r\n  | where toint(customDimensions[\"baseMonitorIdentifiers.length\"]) > 0 \r\n        and tostring(customDimensions['baseMonitorIdentifiers']) != \"\"\r\n  | extend bmIdList = split(customDimensions[\"baseMonitorIdentifiers\"], \",\")\r\n  | mv-expand bmIdList \r\n  | project webId = user_Id, bmId = tostring(bmIdList)\r\n  | distinct webId, bmId;\r\ncustomEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where client_Type != \"SaaS\"\r\n| where timestamp < startofday(now())\r\n| where timestamp > endofday(todatetime(\"${__from:date}\"))\r\n| extend postgresLicenses = toint(customDimensions[\"licensedPostgresEnvironments\"])\r\n| where postgresLicenses > 0\r\n| join kind=inner mappings on $left.user_Id == $right.bmId\r\n| summarize instanceCount = sum(postgresLicenses), customerCount = dcount(webId) by bin(timestamp, 1d)\r\n| extend avgInstancesPerCustomer = todouble(instanceCount)/customerCount\r\n| project timestamp, avgInstancesPerCustomer\r\n| render timechart",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Postgres customers",
   "type": "timeseries",
   "description": "Installations with at least one licensed Postgres entity",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let mappings = customEvents\r\n  | where name == 'monitorinstallation.identifiers'\r\n  | where customDimensions !has 'DeveloperMode'\r\n  | where parse_version( application_Version) > parse_version(\"13.0.15.0\")\r\n  // the 'baseMonitorIdentifiers' field was added in 13.0.15\r\n  // we could look for earlier versions, but we'd need to build the bmIdList using a range \r\n  // e.g. | extend bmIdList = range(0, toint(customDimensions[\"baseMonitorIdentifiers.length\"]-1),1)\r\n  // we can also check this for belt-and-braces: tostring(customDimensions['baseMonitorIdentifiers'])!=\"\"\r\n  | where toint(customDimensions[\"baseMonitorIdentifiers.length\"]) > 0 and tostring(customDimensions['baseMonitorIdentifiers'])!=\"\"\r\n  | extend bmIdList = split(customDimensions[\"baseMonitorIdentifiers\"],\",\")\r\n  | mv-expand bmIdList \r\n  | project webId = user_Id, bmId = tostring(bmIdList)\r\n  | distinct webId, bmId;\r\ncustomEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where client_Type != \"SaaS\" // this caused problems with the Web to Bm mappings and showed one BM attached to hundreds of Websites\r\n| where timestamp < startofday(now())\r\n| where timestamp > endofday(todatetime(\"${__from:date}\"))\r\n| where customDimensions[\"licensedPostgresEnvironments\"]>0\r\n| join kind=inner mappings on $left.user_Id==$right.bmId\r\n| summarize dcount(webId) by bin(timestamp, 1d)\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Users and Stickiness",
   "type": "timeseries",
   "description": "For complete months. Distinct users per working day (mon-fri) : total for month and average per day across the month. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "// weekday stickiness\r\nlet monthlyUsers = customEvents\r\n| where name == \"serveroverview.viewed\"\r\n| where customDimensions !has \"payload.DeveloperMode\"\r\n| where customDimensions[\"payload.serverType\"]==\"PostgresServer\"\r\n| where timestamp > startofmonth(ago(365d)) and timestamp < startofmonth(now())\r\n| extend dayOfWeek = toint(dayofweek(timestamp)/1d)\r\n| where dayOfWeek !in (0,6) // exclude weekends\r\n| summarize totalUsersPerMonth = dcount(user_Id) by month = startofmonth(timestamp);\r\ncustomEvents\r\n| where name == \"serveroverview.viewed\"\r\n| where customDimensions !has \"payload.DeveloperMode\"\r\n| where customDimensions[\"payload.serverType\"]==\"PostgresServer\"\r\n| where timestamp > startofmonth(ago(365d)) and timestamp < startofmonth(now())\r\n| extend dayOfWeek = toint(dayofweek(timestamp)/1d)\r\n| where dayOfWeek !in (0,6) // exclude weekends\r\n| summarize usersPerDay= dcount(user_Id) by day = startofday(timestamp)\r\n| summarize avgUsersPerDay = avg(usersPerDay)by month =startofmonth(day)\r\n| join kind=inner monthlyUsers on $left.month==$right.month\r\n| project month, avgUsersPerDay, totalUsersPerMonth, stickiness=(avgUsersPerDay/totalUsersPerMonth)\r\n| order by month asc",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/RG-Insights-Production/providers/microsoft.insights/components/RG-Insights-Production"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Pure/Native PostgreSQL Customers",
   "type": "stat",
   "description": "Count of installations (websites) which are monitoring at least 8 Postgres instances, and more Postgres than SQL Server.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "// number of installs with majority postgres\r\nlet mappings = customEvents\r\n  | where name == 'monitorinstallation.identifiers'\r\n  | where customDimensions !has 'DeveloperMode'\r\n  | where parse_version( application_Version) > parse_version(\"13.0.15.0\")\r\n  // the 'baseMonitorIdentifiers' field was added in 13.0.15\r\n  // we could look for earlier versions, but we'd need to build the bmIdList using a range \r\n  // e.g. | extend bmIdList = range(0, toint(customDimensions[\"baseMonitorIdentifiers.length\"]-1),1)\r\n  // we can also check this for belt-and-braces: tostring(customDimensions['baseMonitorIdentifiers'])!=\"\"\r\n  | where toint(customDimensions[\"baseMonitorIdentifiers.length\"]) > 0 and tostring(customDimensions['baseMonitorIdentifiers'])!=\"\"\r\n  | extend bmIdList = split(customDimensions[\"baseMonitorIdentifiers\"],\",\")\r\n  | mv-expand bmIdList \r\n  | project webId = user_Id, bmId = tostring(bmIdList)\r\n  | distinct webId, bmId;\r\ncustomEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where timestamp<startofday(now())\r\n| extend postgres=toint(customDimensions[\"postgresInstances\"])\r\n| extend sqlCount=toint(customDimensions[\"sqlServers\"])\r\n| where postgres>7\r\n| summarize arg_max(timestamp, *) by user_Id, day=bin(timestamp, 1d)\r\n| join kind=inner mappings on $left.user_Id==$right.bmId\r\n| summarize totalPg = sum(postgres), totalSql=sum(sqlCount) by webId, day\r\n| extend fractionPg = iff(totalSql==0, 1.0, todouble(totalPg)/todouble(totalPg+totalSql))\r\n| where fractionPg > 0.5\r\n| summarize count() by day\r\n| order by day asc\r\n//| order by fractionPg desc\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  { "title": "Technical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Database Overview Views",
   "type": "timeseries",
   "description": "Count of total views, and distinct WebServers, viewing DatabaseOverview page for PostgreSQL",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"serveroverview.databaseoverview.viewed\"\r\n     or name == \"serveroverview.databasesoverview.viewed\" // event name has changed over time\r\n| where customDimensions !has \"DeveloperMode\"\r\n| extend serverType = tostring(customDimensions[\"serverType\"])\r\n| where serverType == \"PostgresServer\"\r\n| where timestamp >= ago(30d) \r\n| summarize EventCountPerUser=count() by bin(timestamp, 1d), user_Id\r\n| summarize WebServerCount=dcount(user_Id), EventCount=sum(EventCountPerUser) by bin(timestamp, 1d)\r\n| project timestamp, EventCount, WebServerCount\r\n| order by timestamp asc",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Database overview views by page",
   "type": "timeseries",
   "description": "Count of all views, per day, on various parts of the database, table and index details pages",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let databasetab = customEvents\r\n    | where name == \"serveroverview.databasesoverview.viewed\"\r\n    or name == \"serveroverview.databaseoverview.viewed\" // name changed\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"Databases\";\r\nlet database = customEvents\r\n    | where name == \"serveroverview.databasesoverview.databasedetails.viewed\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"Database\";\r\nlet table = customEvents\r\n    | where name == \"serveroverview.databasesoverview.tabledetails.viewed\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"Table\";\r\nlet index = customEvents\r\n    | where name == \"serveroverview.databasesoverview.indexdetails.viewed\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"Index\";\r\ndatabasetab\r\n| union database\r\n| union table\r\n| union index\r\n| where timestamp < startofday(now())\r\n| summarize Clicks = sum(Clicks) by bin(timestamp, 1d), type\r\n| order by timestamp asc\r\n\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "PG Instances Per BaseMonitor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n  | where name == \"monitoredentities.report\"\r\n//  | where customDimensions !has \"DeveloperMode\" // not needed for Rg-Insights-Production\r\n//  | where timestamp > startofday(ago(80d)) and timestamp < endofday(ago(1d))\r\n  | where timestamp<startofday(now()) // only include full days worth of data\r\n  | extend day=bin(timestamp, 1d)\r\n  | summarize arg_max(timestamp, *) by user_Id, day\r\n//   | extend totalServers = toint(customDimensions[\"sqlServers\"])+toint(customDimensions[\"sqlServerInstances\"])\r\n  | extend totalServers = toint(customDimensions[\"postgresInstances\"])\r\n  | where totalServers > 0\r\n  | summarize median=percentile(totalServers,50)\r\n  , mean=avg(totalServers)\r\n  , decile9=percentile(totalServers,90)\r\n  by day",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Index, DB & table page sentiment ",
   "type": "piechart",
   "description": "Data from last 30 days by default.",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\n| where name in (\"serveroverview.databasesoverview.indexdetails.sentiment\"\n,\"serveroverview.databasesoverview.tabledetails.sentiment\"\n,\"serveroverview.databasesoverview.databasedetails.sentiment\")\n| where customDimensions !has \"DeveloperMode\"\n| extend Sentiment = tostring(customDimensions.Sentiment)\n| extend DisplaySentiment = case(\n    Sentiment == \"up\", \"Positive\",\n    Sentiment == \"down\", \"Negative\",\n    Sentiment\n)\n| summarize count() by DisplaySentiment",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Base Monitors with Index Monitoring",
   "type": "piechart",
   "description": "Of those base monitors which have the feature, how many have enabled it. (Last 3 days including today)",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"indexusagesampling.postgres.report\"\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where timestamp > ago(3d)\r\n| extend totalServers = toint(customDimensions[\"totalServerCount\"]), enabledServers=toint(customDimensions[\"samplingEnabledServerCount\"])\r\n| where totalServers >0\r\n| extend someEnabledServer=(enabledServers>0)\r\n| extend hasEnabledIndexes = iff(someEnabledServer, \"Enabled\", \"Not Enabled\")\r\n| summarize arg_max(timestamp, *) by user_Id\r\n| project hasEnabledIndexes, enabledServers\r\n| summarize count() by hasEnabledIndexes\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Base Monitors with Index Monitoring",
   "type": "timeseries",
   "description": "Of those base monitors which have the feature, how many distinct installations have enabled it, each day (ending yesterday to ensure full days worth of data)",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 35 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"indexusagesampling.postgres.report\"\r\n| where customDimensions !has \"DeveloperMode\"\r\n| extend totalServers = toint(customDimensions[\"totalServerCount\"]), enabledServers=toint(customDimensions[\"samplingEnabledServerCount\"])\r\n| where totalServers >0\r\n| where timestamp < startofday(now())\r\n| extend someEnabledServer=(enabledServers>0)\r\n| extend hasEnabledIndexes = iff(someEnabledServer, \"Enabled\", \"Not Enabled\")\r\n| summarize arg_max(timestamp, *) by user_Id, day=bin(timestamp, 1d)\r\n| project hasEnabledIndexes, timestamp\r\n| summarize count() by hasEnabledIndexes, day=bin(timestamp, 1d)\r\n| order by day asc\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Index, table, & DB sentiment by page",
   "type": "barchart",
   "description": "Data from last 30 days by default.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\n| where name in (\"serveroverview.databasesoverview.indexdetails.sentiment\"\n,\"serveroverview.databasesoverview.tabledetails.sentiment\"\n,\"serveroverview.databasesoverview.databasedetails.sentiment\")\n| where customDimensions !has \"DeveloperMode\"\n| extend Sentiment = tostring(customDimensions.Sentiment)\n| extend PageName = case(\n    name == \"serveroverview.databasesoverview.indexdetails.sentiment\", \"Index Details\",\n    name == \"serveroverview.databasesoverview.tabledetails.sentiment\", \"Table Details\",\n    name == \"serveroverview.databasesoverview.databasedetails.sentiment\", \"Database Details\",\n    name\n)\n| extend DisplaySentiment = case(\n    Sentiment == \"up\", \"Positive\",\n    Sentiment == \"down\", \"Negative\",\n    Sentiment\n)\n| summarize count() by PageName, DisplaySentiment",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Postgres overview clicks by object type",
   "type": "timeseries",
   "description": "Count of all clicks, per day, on various parts of the database, table and index details pages",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let database = customEvents\r\n    | where name == \"serveroverview.databasesoverview.database.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"Database\";\r\nlet table = customEvents\r\n    | where name == \"serveroverview.databasesoverview.databasedetails.table.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"Table\";\r\nlet index = customEvents\r\n    | where name == \"serveroverview.databasesoverview.tabledetails.index.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"Index\";\r\nlet dbsBreadcrumb = customEvents\r\n    | where name == \"serveroverview.databasesoverview.breadcrumb.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"DatabasesBreadcrumb\";\r\nlet dbDetailsBreadcrumb = customEvents\r\n    | where name == \"serveroverview.databasesoverview.databasedetails.breadcrumb.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"DatabaseDetailsBreadcrumb\";\r\nlet tableDetailsBreadcrumb = customEvents\r\n    | where name == \"serveroverview.databasesoverview.tabledetails.breadcrumb.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=count() by bin(timestamp, 1d)\r\n    | extend type = \"TableDetailsBreadcrumb\";\r\ndatabase\r\n| union table\r\n| union index\r\n| union dbsBreadcrumb\r\n| union dbDetailsBreadcrumb\r\n| union tableDetailsBreadcrumb\r\n| where timestamp < startofday(now())\r\n| summarize Clicks = sum(Clicks) by bin(timestamp, 1d), type\r\n| order by timestamp asc\r\n\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Postgres overview distinct installs by object type",
   "type": "timeseries",
   "description": "Count of all distinct installs, per day, on various parts of the database, table and index details pages (\"user\" = \"website id\")",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let database = customEvents\r\n    | where name == \"serveroverview.databasesoverview.database.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=dcount(user_Id) by bin(timestamp, 1d)\r\n    | extend type = \"Database\";\r\nlet table = customEvents\r\n    | where name == \"serveroverview.databasesoverview.databasedetails.table.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=dcount(user_Id) by bin(timestamp, 1d)\r\n    | extend type = \"Table\";\r\nlet index = customEvents\r\n    | where name == \"serveroverview.databasesoverview.tabledetails.index.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=dcount(user_Id) by bin(timestamp, 1d)\r\n    | extend type = \"Index\";\r\nlet dbsBreadcrumb = customEvents\r\n    | where name == \"serveroverview.databasesoverview.breadcrumb.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=dcount(user_Id) by bin(timestamp, 1d)\r\n    | extend type = \"DatabasesBreadcrumb\";\r\nlet dbDetailsBreadcrumb = customEvents\r\n    | where name == \"serveroverview.databasesoverview.databasedetails.breadcrumb.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=dcount(user_Id) by bin(timestamp, 1d)\r\n    | extend type = \"DatabaseDetailsBreadcrumb\";\r\nlet tableDetailsBreadcrumb = customEvents\r\n    | where name == \"serveroverview.databasesoverview.tabledetails.breadcrumb.clicked\"\r\n    | where customDimensions !has \"DeveloperMode\"\r\n    | where customDimensions[\"engine\"] == \"PostgresDatabase\"\r\n    | summarize Clicks=dcount(user_Id) by bin(timestamp, 1d)\r\n    | extend type = \"TableDetailsBreadcrumb\";\r\ndatabase\r\n| union table\r\n| union index\r\n| union dbsBreadcrumb\r\n| union dbDetailsBreadcrumb\r\n| union tableDetailsBreadcrumb\r\n| where timestamp < startofday(now())\r\n| summarize Clicks = sum(Clicks) by bin(timestamp, 1d), type\r\n| order by timestamp asc",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Postgres versions currently monitored by %",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents \r\n| where customDimensions !has 'DeveloperMode'\r\n| where name == \"monitoredentities.versions\"\r\n| where customDimensions['entityType'] == 'PostgresInstance'\r\n| where timestamp < endofday(ago(1d)) and timestamp > startofday(ago(1d))\r\n| extend majorVersion = tostring(customDimensions[\"oneDot\"]) \r\n| extend fullVersion = tostring(customDimensions[\"version\"]) \r\n| extend day = bin(timestamp, 1d)\r\n| extend instanceCount = toint(customDimensions[\"count\"])\r\n| summarize arg_max(timestamp, *) by user_Id, day, fullVersion \r\n| summarize instances = sum(instanceCount) by majorVersion\r\n| project Name = strcat(\"PostgreSQL v\", majorVersion), Count = instances\r\n| order by Name asc",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Postgres versions currently monitored",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents \r\n| where customDimensions !has 'DeveloperMode'\r\n| where name == \"monitoredentities.versions\"\r\n| where customDimensions['entityType'] == 'PostgresInstance'\r\n| where timestamp < endofday(ago(1d)) and timestamp > startofday(ago(1d))\r\n| extend majorVersion = tostring(customDimensions[\"oneDot\"]) \r\n| extend fullVersion = tostring(customDimensions[\"version\"]) \r\n| extend day = bin(timestamp, 1d)\r\n| extend instanceCount = toint(customDimensions[\"count\"])\r\n| summarize arg_max(timestamp, *) by user_Id, day, fullVersion \r\n| summarize instances = sum(instanceCount) by majorVersion\r\n| project Name = strcat(\"PostgreSQL v\", majorVersion), Count = instances\r\n| order by Name asc",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Base Monitor Versions with monitored Postgres entities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }
  },
  {
   "title": "Replica Node Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == 'postgres.replication'\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| where timestamp < endofday( ago(1d) )\r\n| summarize sendingInstanceCount=max(toint(customDimensions[\"sendingInstanceCount\"])),\r\nreceivingInstanceCount=max(toint(customDimensions[\"receivingInstanceCount\"])),\r\ncascadingInstanceCount=max(toint(customDimensions[\"cascadingInstanceCount\"]))\r\nby user_Id, bin(timestamp,1d)\r\n| summarize sendingReplica = sum(sendingInstanceCount),\r\nreceivingReplica = sum(receivingInstanceCount),\r\ncascadingReplica = sum(cascadingInstanceCount)\r\nby timestamp\r\n| order by timestamp asc\r\n\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Sessions for available Postgres Features",
   "type": "timeseries",
   "description": "Sessions for instances monitoring Postgres entities broken down by released features they have available",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| where name == \"monitoredentities.versions\"\r\n| where customDimensions['entityType'] == 'PostgresInstance'\r\n| where timestamp < endofday(ago(1d))\r\n| extend major = toint(split(application_Version, \".\")[0])\r\n| extend minor = toint(split(application_Version, \".\")[1])\r\n| extend build = toint(split(application_Version, \".\")[2])\r\n// | extend minorX = case(strlen(minor) == 1, strcat(\"0\", minor), minor)\r\n// | extend buildX = case(strlen(build) == 1, strcat(\"0\", build), build)\r\n// | extend majorMinor = strcat(major, \".\", minorX, \".\", buildX)\r\n| extend ibuild = toint(build)\r\n| where toint(major) > 12\r\n| extend ver = case(\r\n                   (major == 13 and ibuild < 10),\r\n                   \"13.0.00 PostgreSQL Linux and RDS\",\r\n                   (major == 13 and ibuild < 15),\r\n                   \"13.0.10 First alerts\",\r\n                   (major == 13 and ibuild < 27),\r\n                   \"13.0.15 Replication\",\r\n                   (major == 13 and ibuild < 35),\r\n                   \"13.0.27 Aurora\",\r\n                   (major == 13 and ibuild < 42),\r\n                   \"13.0.35 Postgres 16\",\r\n                   (major == 13 and ibuild < 43),\r\n                   \"13.0.42 Configuration\",\r\n                   (major == 13 and ibuild < 44),\r\n                   \"13.0.43 Autovacuum\",\r\n                   (major == 13 and ibuild < 53),\r\n                   \"13.0.44 Recommendations\",\r\n                   (major == 13) or (major == 14 and minor == 0 and ibuild < 4),\r\n                   \"13.0.53 More alerts\",\r\n                   (major == 14 and minor == 0 and ibuild < 5),\r\n                   \"14.0.04 Queryplan Changes\",\r\n                   (major == 14 and minor == 0 and ibuild < 10),\r\n                   \"14.0.05 IAM support\",\r\n                   (major == 14 and minor == 0 and ibuild < 27),\r\n                   \"14.0.10 Current Activity\",\r\n                   (major == 14 and minor == 0 and ibuild < 30),\r\n                   \"14.0.27 Low cache hit ratio\",\r\n                   (major == 14 and minor == 0 and ibuild < 32),\r\n                   \"14.0.30 Postgres 17\",\r\n                   (major == 14 and minor == 0 and ibuild < 34),\r\n                   \"14.0.32 NFS\",\r\n                   (major == 14 and minor == 0 and ibuild < 39),\r\n                   \"14.0.34 Azure Flex\",\r\n                   (major == 14 and minor == 0 and ibuild < 40),\r\n                   \"14.0.39 Entra Powershell\",\r\n                   (major == 14 and minor == 0 and ibuild < 42),\r\n                   \"14.0.40 Flex Query Plans & Entra ID\",\r\n                   (major == 14 and minor == 0 and ibuild < 56),\r\n                   \"14.0.42 Log Entry Alerts\",\r\n                   (major == 14 and minor == 0 and ibuild < 58),\r\n                   \"14.0.56 Indexes FUR\",\r\n                   (major == 14 and minor == 0 and ibuild < 66),\r\n                   \"14.0.58 Databases Tab\",\r\n                   (major == 14 and minor == 0 and ibuild < 67),\r\n                   \"14.0.66 Index Monitoring\",\r\n                   (major == 14 and minor == 0 and ibuild < 68), \"14.0.67 Index CTA and Sentiment\",\r\n                   (major == 14 and minor == 0 and ibuild < 71), \"14.0.68 Test Add Server pt1\",\r\n                   (major == 14 and minor == 0 and ibuild < 73), \"14.0.71 Missing TQ, QP diag\",\r\n                   (major == 14 and (minor == 0 or minor ==1)), \"14.0.73 diagnose & test FUR\",\r\n                   (major == 14 and minor < 4), \"14.2.0 custom metrics\",\r\n                   \"14.4.0 PostgreSQL 18\"\r\n               )\r\n| summarize sessions=dcount(session_Id) by bin(timestamp, 1d), ver \r\n| order by timestamp asc, ver\r\n\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": {
      "query": "customEvents\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| extend major = tostring(split(application_Version, \".\")[0])\r\n| extend minor = tostring(split(application_Version, \".\")[1])\r\n| extend build = tostring(split(application_Version, \".\")[2])\r\n| extend minorX = case(strlen(minor) == 1, strcat(\"0\", minor), minor)\r\n| extend buildX = case(strlen(build) == 1, strcat(\"0\", build), build)\r\n| extend majorMinor = strcat(major, \".\", minorX, \".\", buildX)\r\n| extend ver = case(major==13, majorMinor,\r\n                    major==12, \"v12\",\r\n                    \"v11 and lower\")\r\n| summarize sessions=dcount(session_Id) by bin(timestamp, 1d), ver \r\n| order by bin(timestamp, 1d) asc, ver ",
      "resultFormat": "time_series"
     },
     "subscription": "64865690-933f-4328-9a41-6b2f546777af"
    }
   ]
  },
  {
   "title": "Session count by Monitor version",
   "type": "timeseries",
   "description": "Session count for base monitors monitoring Postgres, by version",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| where client_Type != \"SaaS\"\r\n| where name == \"monitoredentities.versions\"\r\n| where customDimensions['entityType'] == 'PostgresInstance'\r\n| where timestamp < endofday( ago(1d) )\r\n| extend major = tostring(split(application_Version, \".\")[0])\r\n| extend minor = tostring(split(application_Version, \".\")[1])\r\n| extend build = tostring(split(application_Version, \".\")[2])\r\n| extend minorX = case(strlen(minor) == 1, strcat(\"0\", minor), minor)\r\n| extend buildX = case(strlen(build) == 1, strcat(\"0\", build), build)\r\n| extend majorMinor = strcat(major, \".\", minorX, \".\", buildX)\r\n| extend ver = case(major==11, \"11.x\",\r\n                    major==12, \"12.x\",\r\n                    (major==13 and toint(build)<=40), \"13.00.40 or lower\",\r\n                    major==13, \"13.00.41 or higher\",\r\n                    (major==14 and minor==0 and toint(build)<=10), \"14.00.10 or lower\",\r\n                    (major==14 and minor==0 and toint(build)<=39), \"14.00.39 or lower\",\r\n                    majorMinor)\r\n| summarize sessions=dcount(session_Id) by day=bin(timestamp, 1d), ver \r\n| order by day asc\r\n// | order by ver desc\r\n//| render stackedArea\r\n\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": {
      "query": "customEvents\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| extend major = tostring(split(application_Version, \".\")[0])\r\n| extend minor = tostring(split(application_Version, \".\")[1])\r\n| extend build = tostring(split(application_Version, \".\")[2])\r\n| extend minorX = case(strlen(minor) == 1, strcat(\"0\", minor), minor)\r\n| extend buildX = case(strlen(build) == 1, strcat(\"0\", build), build)\r\n| extend majorMinor = strcat(major, \".\", minorX, \".\", buildX)\r\n| extend ver = case(major==13, majorMinor,\r\n                    major==12, \"v12\",\r\n                    \"v11 and lower\")\r\n| summarize sessions=dcount(session_Id) by bin(timestamp, 1d), ver \r\n| order by bin(timestamp, 1d) asc, ver ",
      "resultFormat": "time_series"
     },
     "subscription": "64865690-933f-4328-9a41-6b2f546777af"
    }
   ]
  },
  { "title": "Simon is tinkering with things", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Base Monitors by version",
   "type": "piechart",
   "description": "And whether or not they are monitoring any PostgreSQL instances",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where name == \"monitoredentities.report\"\r\n| where timestamp > ago(7d)\r\n| extend hasSomePostgres=case(customDimensions[\"postgresInstances\"]>0, \"SomePostgres\", \"NoPostgres\") \r\n| extend major = tostring(split(application_Version, \".\")[0])\r\n| summarize arg_max(timestamp, *) by user_Id\r\n| summarize count() by usage=strcat(\"Monitor-v\",major,\"-\",hasSomePostgres)\r\n| order by usage\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Installations with at least one licensed Postgres entity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let mappings = customEvents\r\n  | where name == 'monitorinstallation.identifiers'\r\n  | where customDimensions !has 'DeveloperMode'\r\n  | where parse_version( application_Version) > parse_version(\"13.0.15.0\")\r\n  // the 'baseMonitorIdentifiers' field was added in 13.0.15\r\n  // we could look for earlier versions, but we'd need to build the bmIdList using a range \r\n  // e.g. | extend bmIdList = range(0, toint(customDimensions[\"baseMonitorIdentifiers.length\"]-1),1)\r\n  // we can also check this for belt-and-braces: tostring(customDimensions['baseMonitorIdentifiers'])!=\"\"\r\n  | where toint(customDimensions[\"baseMonitorIdentifiers.length\"]) > 0 and tostring(customDimensions['baseMonitorIdentifiers'])!=\"\"\r\n  | extend bmIdList = split(customDimensions[\"baseMonitorIdentifiers\"],\",\")\r\n  | mv-expand bmIdList \r\n  | project webId = user_Id, bmId = tostring(bmIdList)\r\n  | distinct webId, bmId;\r\ncustomEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where timestamp < startofday(now())\r\n| where timestamp > endofday(todatetime(\"${__from:date}\"))\r\n| where customDimensions[\"licensedPostgresEnvironments\"]>0\r\n| join kind=inner mappings on $left.user_Id==$right.bmId\r\n| summarize dcount(webId) by day=bin(timestamp, 1d)\r\n| order by day asc\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Postgres ServerOverview users",
   "type": "barchart",
   "description": "By Month",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 87 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let GetMonthName = (monthofyear:int) {\r\n    case(\r\n        monthofyear == 1, \"January\",\r\n        monthofyear == 2, \"February\",\r\n        monthofyear == 3, \"March\",\r\n        monthofyear == 4, \"April\",\r\n        monthofyear == 5, \"May\",\r\n        monthofyear == 6, \"June\",\r\n        monthofyear == 7, \"July\",\r\n        monthofyear == 8, \"August\",\r\n        monthofyear == 9, \"September\",\r\n        monthofyear == 10, \"October\",\r\n        monthofyear == 11, \"November\",\r\n        monthofyear == 12, \"December\",\r\n        \"Invalid Month\" // fallback for values outside 1–12\r\n    )\r\n};\r\ncustomEvents\r\n| where name == \"serveroverview.viewed\"\r\n| where customDimensions !has \"payload.DeveloperMode\"\r\n| where customDimensions[\"payload.serverType\"]==\"PostgresServer\"\r\n//| where timestamp>startofmonth(ago(120d))\r\n| extend monthNum = monthofyear(timestamp)\r\n| summarize dcount(user_Id), monthNum=max(monthNum) by yearMonth=format_datetime(timestamp, \"yyyy-MM\")\r\n| order by yearMonth asc\r\n| project GetMonthName(monthNum),Users=dcount_user_Id",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/RG-Insights-Production/providers/microsoft.insights/components/RG-Insights-Production"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Postgres ServerOverview users (MAU)",
   "type": "stat",
   "description": "By Month",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let GetMonthName = (monthofyear:int) {\r\n    case(\r\n        monthofyear == 1, \"January\",\r\n        monthofyear == 2, \"February\",\r\n        monthofyear == 3, \"March\",\r\n        monthofyear == 4, \"April\",\r\n        monthofyear == 5, \"May\",\r\n        monthofyear == 6, \"June\",\r\n        monthofyear == 7, \"July\",\r\n        monthofyear == 8, \"August\",\r\n        monthofyear == 9, \"September\",\r\n        monthofyear == 10, \"October\",\r\n        monthofyear == 11, \"November\",\r\n        monthofyear == 12, \"December\",\r\n        \"Invalid Month\" // fallback for values outside 1–12\r\n    )\r\n};\r\ncustomEvents\r\n| where name == \"serveroverview.viewed\"\r\n| where customDimensions !has \"payload.DeveloperMode\"\r\n| where customDimensions[\"payload.serverType\"]==\"PostgresServer\"\r\n//| where timestamp>startofmonth(ago(120d))\r\n| extend monthNum = monthofyear(timestamp)\r\n| summarize dcount(user_Id), monthNum=max(monthNum) by yearMonth=format_datetime(timestamp, \"yyyy-MM\")\r\n| order by yearMonth desc \r\n| take 2\r\n| order by yearMonth asc\r\n| take 1\r\n| project GetMonthName(monthNum),Users=dcount_user_Id\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/RG-Insights-Production/providers/microsoft.insights/components/RG-Insights-Production"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Base Monitors by Monitored PG instances",
   "type": "barchart",
   "description": "Recently seen BMs",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 95 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where name==\"monitoredentities.report\"\r\n| where customDimensions[\"postgresInstances\"]>0\r\n| where timestamp > ago(3d) // show only most recently seen BMs\r\n| extend postgresInstances=toint(customDimensions[\"postgresInstances\"])\r\n| summarize arg_max(timestamp, *) by user_Id\r\n| summarize BaseMonitors=count() by postgresInstances\r\n| project postgresInstances, BaseMonitors\r\n| order by postgresInstances asc",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Customers looking at Database Overview",
   "type": "timeseries",
   "description": "Per Monitor Version",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 95 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"serveroverview.databasesoverview.viewed\" \r\nor name == \"serveroverview.databaseoverview.viewed\"\r\nor name == \"serveroverview.databasesoverview.databasedetails.viewed\"\r\n| where customDimensions !has \"DeveloperMode\"\r\n| extend ver = strcat_array(array_slice(split(application_Version, \".\"), 0, 2), \".\")\r\n| summarize dcount(user_Id) by ver, day=bin(timestamp, 1d)\r\n| project day, websites=dcount_user_Id, version=ver\r\n| order by day asc, version\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "All RG Monitor Installs",
   "type": "timeseries",
   "description": "Count of websites by Monitor Major+Minor and a rounded patch version",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where timestamp < startofday(now())\r\n| where customDimensions[\"componentId\"]==\"web-server\"\r\n| summarize arg_max(timestamp, *) by user_Id, bin(timestamp, 1d)\r\n//| extend version = strcat_array(array_slice(split(application_Version,\".\"), 0, 1), \".\")\r\n| extend majorVer = (split(application_Version,\".\"))[0]\r\n| extend minorVer = (split(application_Version,\".\"))[1]\r\n| extend patchVer = (split(application_Version,\".\"))[2]\r\n| extend roundedPatch = patchVer - (patchVer % 10)\r\n| extend version = strcat(majorVer, \".\", minorVer, \".\", roundedPatch, \"+\")\r\n| summarize count() by version, day=bin(timestamp, 1d)\r\n| order by day asc",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  { "title": "Diagnose", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Top query diagnose results",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name in (\"serveroverview.topqueries.diagnoseresults\")\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where customDimensions has \"AllTestsPassed\"\r\n| summarize count(customDimensions[\"AllTestsPassed\"] == true), count(customDimensions[\"AllTestsPassed\"] == false)",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Query plans diagnose results",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name in (\"serveroverview.queryplans.diagnoseresults\")\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where customDimensions has \"AllTestsPassed\"\r\n| summarize count(customDimensions[\"AllTestsPassed\"] == true), count(customDimensions[\"AllTestsPassed\"] == false)",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Add server tests ",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 104 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"configuration.monitoredservers.test.v2\"\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where customDimensions[\"entityType\"] == \"PostgresInstance\"\r\n| extend testResultsKeys = bag_keys(customDimensions)\r\n| where array_length(array_slice(testResultsKeys, 0, array_length(testResultsKeys))) > 0\r\n| mv-apply bagItem = bag_keys(customDimensions) to typeof(string) on (\r\n    where bagItem startswith \"testResults.\" and bagItem !contains \" \" and bagItem !contains \"EntityTestCaseResult\"\r\n    | extend TestName = replace_string(bagItem, \"testResults.\", \"\")\r\n    | extend Success = tobool(customDimensions[bagItem])\r\n    | project TestName, Success\r\n)\r\n| where isnotempty(TestName) and isnotnull(Success)\r\n| summarize Count = count() by TestName, Success\r\n| evaluate pivot(Success, sum(Count))\r\n| render columnchart by TestName",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Top query diagnose failures",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name in (\"serveroverview.topqueries.diagnoseresults\")\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where customDimensions has \"IsPgMonitorRoleGranted\"\r\n| where customDimensions has \"IsTrackingStatements\"\r\n| where customDimensions has \"IsPgStatStatementsLoaded\"\r\n| where customDimensions has \"IsPgStatStatementsEnabled\"\r\n| summarize count(customDimensions[\"IsPgMonitorRoleGranted\"] == false), count(customDimensions[\"IsTrackingStatements\"] == false), count(customDimensions[\"IsPgStatStatementsLoaded\"] == false), count(customDimensions[\"IsPgStatStatementsEnabled\"] == false)",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Query plans diagnose failures",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name in (\"serveroverview.queryplans.diagnoseresults\")\r\n| where customDimensions !has \"DeveloperMode\"\r\n| where customDimensions has \"IsAutoExplainEnabled\"\r\n| where customDimensions has \"IsLoggingCollectorEnabled\"\r\n| where customDimensions has \"IsLogLevelCorrect\"\r\n| where customDimensions has \"IsLogDestinationCsv\"\r\n| where customDimensions has \"IsLogFormatJson\"\r\n| where customDimensions has \"IsLogPrefixCorrect\"\r\n| where customDimensions has \"IsAutoExplainEnabled\"\r\n| where customDimensions has \"CurrentLogMinDuration\"\r\n| where customDimensions has \"CurrentSampleRate\"\r\n| where customDimensions has \"IsAdvancedMonitoringEnabled\"\r\n| where customDimensions has \"IsFdwExtensionInstalled\"\r\n| summarize count(customDimensions[\"IsAutoExplainEnabled\"] == false), \r\ncount(customDimensions[\"IsLoggingCollectorEnabled\"] == false), \r\ncount(customDimensions[\"IsLogLevelCorrect\"] == false), \r\ncount(customDimensions[\"IsLogDestinationCsv\"] == false), \r\ncount(customDimensions[\"IsLogFormatJson\"] == false), \r\ncount(customDimensions[\"IsLogPrefixCorrect\"] == false), \r\ncount(customDimensions[\"CurrentLogMinDuration\"] == 0), \r\ncount(customDimensions[\"CurrentSampleRate\"] == 0), \r\ncount(customDimensions[\"IsAdvancedMonitoringEnabled\"] == false),\r\ncount(customDimensions[\"IsFdwExtensionInstalled\"] == false)",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Diagnostic sentiment by page",
   "type": "barchart",
   "description": "Data from last 30 days by default.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 114 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\n| where name in (\"serveroverview.queryplans.diagnose.sentiment\"\n,\"serveroverview.topqueries.diagnose.sentiment\")\n| where customDimensions !has \"DeveloperMode\"\n| extend Sentiment = tostring(customDimensions.Sentiment)\n| extend PageName = case(\n    name == \"serveroverview.queryplans.diagnose.sentiment\", \"Query plans\",\n    name == \"serveroverview.topqueries.diagnose.sentiment\", \"Top queries\",\n    name\n)\n| extend DisplaySentiment = case(\n    Sentiment == \"up\", \"Positive\",\n    Sentiment == \"down\", \"Negative\",\n    Sentiment\n)\n| summarize count() by PageName, DisplaySentiment",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  { "title": "Authentication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "\"Add a server\" tests for certificate instances (inlcudes dev)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 124 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name in (\"configuration.monitoredservers.test.v2\")\r\n| summarize count(customDimensions[\"extraProperties.AuthenticationMode\"] == \"Certificate\" and customDimensions[\"result\"] == true),\r\ncount(customDimensions[\"extraProperties.AuthenticationMode\"] == \"Certificate\" and customDimensions[\"result\"] == false)",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Postgres instances by authentication mode (includes dev)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 7, "y": 124 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"monitoredentities.report\"\r\n| summarize arg_max(timestamp, numPostgresInstances=toint(customDimensions[\"postgresInstances\"])), \r\narg_max(timestamp, numPasswordInstances=toint(customDimensions[\"totalPostgresInstancesUsingPostgresAuth\"])),\r\narg_max(timestamp, numCertInstances=toint(customDimensions[\"totalPostgresInstancesUsingCertificateAuth\"])),\r\narg_max(timestamp, numIAMInstances=toint(customDimensions[\"totalPostgresInstancesUsingIamAuth\"])) by user_Id, bin(timestamp, 1d)  \r\n| where numPostgresInstances > 0\r\n| summarize\r\n    total_postgres_instances=sum(numPostgresInstances),\r\n    password_postgres_instances=sum(numPasswordInstances),\r\n    cert_postgres_instances=sum(numCertInstances),\r\n    iam_postgres_instance=sum(numIAMInstances)\r\n    by bin(timestamp, 1d)\r\n\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Instances seen yesterday by Authentication Mode",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 134 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| where bin(timestamp, 1d) == bin(now(-1d), 1d)\r\n| summarize arg_max(timestamp, numPostgresInstances=toint(customDimensions[\"postgresInstances\"])), \r\narg_max(timestamp, numPasswordInstances=toint(customDimensions[\"totalPostgresInstancesUsingPostgresAuth\"])),\r\narg_max(timestamp, numCertInstances=toint(customDimensions[\"totalPostgresInstancesUsingCertificateAuth\"])),\r\narg_max(timestamp, numIAMInstances=toint(customDimensions[\"totalPostgresInstancesUsingIamAuth\"])) by user_Id\r\n| summarize\r\n    Password=sum(numPasswordInstances),\r\n    IAM=sum(numIAMInstances),\r\n    Certificate=sum(numCertInstances)\r\n\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Postgres instances by authentication mode (excludes Dev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 7, "y": 134 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| summarize arg_max(timestamp, numPostgresInstances=toint(customDimensions[\"postgresInstances\"])), \r\narg_max(timestamp, numPasswordInstances=toint(customDimensions[\"totalPostgresInstancesUsingPostgresAuth\"])),\r\narg_max(timestamp, numCertInstances=toint(customDimensions[\"totalPostgresInstancesUsingCertificateAuth\"])),\r\narg_max(timestamp, numIAMInstances=toint(customDimensions[\"totalPostgresInstancesUsingIamAuth\"])) by user_Id, bin(timestamp, 1d)  \r\n| where numPostgresInstances > 0\r\n| summarize\r\n    total_postgres_instances=sum(numPostgresInstances),\r\n    password_postgres_instances=sum(numPasswordInstances),\r\n    cert_postgres_instances=sum(numCertInstances),\r\n    iam_postgres_instance=sum(numIAMInstances)\r\n    by bin(timestamp, 1d)\r\n\r\n",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Custom metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "collapsed": true,
   "panels": [
    {
     "title": "Custom metrics targeting Postgres",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": true,
        "query": "customEvents\r\n| where name == \"custommetrics.report\"\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| summarize arg_max(timestamp, numPostgresCustomMetrics=toint(customDimensions[\"postgresCustomMetricsCount\"])), \r\narg_max(timestamp, numActive=toint(customDimensions[\"activePostgresMetricsCount\"])) by user_Id, bin(timestamp, 1d)  \r\n| where numPostgresCustomMetrics > 0\r\n| summarize\r\n    total_postgres_custom_metrics=sum(numPostgresCustomMetrics),\r\n    total_active=sum(numActive)\r\n    by bin(timestamp, 1d)\r\n\r\n",
        "resources": [
         "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
        ],
        "resultFormat": "time_series",
        "timeColumn": "timestamp"
       }
      }
     ]
    },
    {
     "title": "Custom metrics created over last time period",
     "type": "piechart",
     "description": "Defaults to 30d",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": true,
        "query": "customEvents\r\n| where name == \"custommetrics.newmetriccreated\"\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| summarize \r\n    postgres_metrics=count(customDimensions[\"targetEntityType\"] == \"Postgres\"), \r\n    sqlserver_metrics=count(customDimensions[\"targetEntityType\"] == \"SqlServer\")\r\n",
        "resources": [
         "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
        ],
        "resultFormat": "time_series",
        "timeColumn": "timestamp"
       }
      }
     ]
    }
   ]
  },
  { "title": "Polymon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Total Number of PostgreSQL Tracked Queries",
   "type": "timeseries",
   "description": "The total number of PostgreSQL tracked queries across all instances for all users.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "customEvents \r\n| where name == \"serveroverview.trackedqueries.report\" \r\n| where tostring(customDimensions[\"DeveloperMode\"]) != \"true\"\r\n| extend trackedQueryCount = toint(customDimensions[\"PostgresInstance\"]) \r\n| summarize trackedQueryCount = max(trackedQueryCount) by bin(timestamp, 1d), user_Id, tostring(customDimensions[\"instance\"])\r\n| summarize sum(trackedQueryCount) by bin(timestamp, 1d)\r\n| render timechart",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "PostgreSQL Tracked Queries - Track vs Untrack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "customEvents\r\n| where tostring(customDimensions[\"DeveloperMode\"]) != \"true\"\r\n| summarize tracked_queries = countif(name == \"serveroverview.trackedqueries.postgres.track\"), untracked_queries = countif(name == \"serveroverview.trackedqueries.postgres.untrack\") by bin(timestamp, 1d)\r\n| render timechart",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Total Number of PostgreSQL Tracked Queries (includes dev)",
   "type": "timeseries",
   "description": "The total number of PostgreSQL tracked queries across all instances for all users.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "customEvents \r\n| where name == \"serveroverview.trackedqueries.report\" \r\n| extend trackedQueryCount = toint(customDimensions[\"PostgresInstance\"]) \r\n| summarize trackedQueryCount = max(trackedQueryCount) by bin(timestamp, 1d), user_Id, tostring(customDimensions[\"instance\"])\r\n| summarize sum(trackedQueryCount) by bin(timestamp, 1d)\r\n| render timechart",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "PostgreSQL Tracked Queries - Track vs Untrack (includes dev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "customEvents\r\n| summarize tracked_queries = countif(name == \"serveroverview.trackedqueries.postgres.track\"), untracked_queries = countif(name == \"serveroverview.trackedqueries.postgres.untrack\") by bin(timestamp, 1d)\r\n| render timechart",
      "resources": [
       "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Archived",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of monitored PostgreSQL instances and base monitors with a PostgreSQL instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "customEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| where timestamp < endofday(ago(1d))\r\n| summarize arg_max(timestamp, numPostgresInstances=toint(customDimensions[\"postgresInstances\"])) by user_Id, bin(timestamp, 1d)\r\n| where numPostgresInstances > 0\r\n| summarize\r\n    total_postgres_instances=sum(numPostgresInstances),\r\n    base_monitor_count=dcount(user_Id)\r\n    by bin(timestamp, 1d)\r\n//| render timechart\r\n",
        "resources": [
         "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
        ],
        "resultFormat": "time_series"
       }
      }
     ]
    },
    {
     "title": "Monitored PostgreSQL Instances",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 171 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "customEvents\r\n| where name == \"monitoredentities.report\"\r\n| where customDimensions[\"DeveloperMode\"] != true\r\n| where timestamp < endofday(ago(1d))\r\n| summarize arg_max(timestamp, numPostgresInstances=toint(customDimensions[\"postgresInstances\"])) by user_Id, bin(timestamp, 1d)\r\n| where numPostgresInstances > 0\r\n| summarize\r\n    sum(numPostgresInstances)//,\r\n//    base_monitor_count=dcount(user_Id)\r\n    by day=bin(timestamp, 1d)\r\n| order by day\r\n//| render timechart\r\n",
        "resources": [
         "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/monitor/providers/Microsoft.Insights/components/monitor"
        ],
        "resultFormat": "time_series"
       }
      }
     ]
    },
    {
     "title": "Stickiness ",
     "type": "timeseries",
     "description": "DAU / MAU. Activity Engagement using Azure's built-in function for UserIds over a rolling 30d window. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "customEvents\r\n| where name == \"serveroverview.viewed\"\r\n| where customDimensions !has \"payload.DeveloperMode\"\r\n| where customDimensions[\"payload.serverType\"]==\"PostgresServer\"\r\n| where timestamp > ago(90d)\r\n| evaluate activity_engagement(user_Id, timestamp, ago(90d), ago(1d), 1d, 30d)\r\n| project timestamp, activity_ratio\r\n| where timestamp > ago(60d)\r\n| order by timestamp asc",
        "resources": [
         "/subscriptions/64865690-933f-4328-9a41-6b2f546777af/resourceGroups/RG-Insights-Production/providers/microsoft.insights/components/RG-Insights-Production"
        ],
        "resultFormat": "time_series"
       }
      }
     ]
    }
   ]
  }
 ]
}